version: "3"
services:

  # Mariadb DataBase
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - /home/fel-boua/data/db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fatine_net
    env_file:
      - .env

  # Nginx Web Server
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /home/fel-boua/data/wp-data:/www/wordpress
    ports:
      - "443:443"
    networks:
      - fatine_net
    env_file:
      - .env
  
  # WordPress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always 
    depends_on:
      - nginx
    volumes:
      - /home/fel-boua/data/wp-data:/www/wordpress
    ports:
      - "9000:9000"
    networks:
      - fatine_net
    env_file:
      - .env

  # Adminer
  adminer:
    build: ./requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - /home/fel-boua/data/db-data:/var/lib/mysql
    networks:
      - fatine_net

  # # Portfolio
  # portfolio:
  #   build: ./requirements/bonus/portfolio/
  #   image: portfolio
  #   container_name: portfolio
  #   restart: always
  #   ports:
  #     - '5001:80'
  #   networks:
  #     - fatine_net

  # FTP
  # ftp:
  #   build: ./requirements/bonus/ftp/
  #   image: ftp
  #   container_name: ftp
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - /home/fel-boua/data/wp-data:/www/wordpress
  #   ports:
  #     - '2211:21'
  #     - '21000-22000:21000-22000'
  #   networks:
  #     - fatine_net

  # Game
  game:
    build: ./requirements/bonus/game/
    image: game
    container_name: game
    restart: always
    ports:
      - 5010:80
    networks:
      - fatine_net
      
  # WebSite
  website:
    build: ./requirements/bonus/website/
    image: website
    container_name: website
    restart: always
    ports:
      - 5020:80
    networks:
      - fatine_net
  
  # Redis
  redis:
    build: ./requirements/bonus/redis/
    image: redis
    container_name: redis
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - /home/fel-boua/data/wp-data:/www/wordpress
    ports:
      - '6379:6379'
    networks:
      - fatine_net

networks:
  fatine_net:
